# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
# import sphinx_adc_theme


# -- Project information -----------------------------------------------------

project = 'Machine Learning Fundation'
copyright = '2022-2024, SSPUIIP'
author = 'SSPUIIP'

# The full version, including alpha/beta/rc tags
release = '1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.mermaid', 
    'sphinx_copybutton',
    'myst_parser',
    'sphinx_design',
    'sphinx_togglebutton',
    'sphinx.ext.mathjax',
    'sphinx-mathjax-offline',  ]
    #'rst2pdf.pdfbuilder',  # pdf生成 make latexpdf
#]
#    "jupyter_sphinx",   
#]

latex_engine = 'xelatex'  # pdf生成

# 中文pdf配置
latex_elements={
    'papersize':'a4paper',
    'pointsize':'8pt',
    'fontpkg':r'''
        \usepackage{xltxtra,fontspec,xunicode}
        \usepackage[slantfont,boldfont]{xeCJK}
        \usepackage{fontspec}
        \setCJKmainfont[BoldFont=SimHei,ItalicFont=KaiTi]{FangSong}
    '''
}


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases. 
# 'zh_CN', 'en'
language = 'zh_CN'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build']

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'markdown',
    '.md': 'markdown'
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#  'alabaster' 'sphinx_rtd_theme' 'sphinx_book_theme' 'furo' 'piccolo_theme' 
#   classic scrolls sphinxdoc nature haiku bizstyle pyramid agogo traditional

html_theme = 'furo'

# html_theme = 'sphinx_adc_theme'
# html_theme_path = [sphinx_adc_theme.get_html_theme_path()]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# mathjax_options ={
#    "math_number_all": "True",
#    "math_eqref_format": "True"
# }


# -- Extension configuration -------------------------------------------------
myst_enable_extensions = [
    "amsmath",
    "attrs_inline",
    "attrs_block",
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# -- mermaid
mermaid_version = '10.8.0'



 
